const superheroes = [
  {
    name: "Superman",
    age: 35,
    city: "Metropolis",
    realName: "Clark Kent",
    superPower: 98,
    species: "Kryptonian",
    company: "DC",
  },
  {
    name: "Batman",
    age: 40,
    city: "Gotham",
    realName: "Bruce Wayne",
    superPower: 85,
    species: "Human",
    company: "DC",
  },
  {
    name: "Wonder Woman",
    age: 3000,
    city: "Themyscira",
    realName: "Diana Prince",
    superPower: 95,
    species: "Amazon/Demigod",
    company: "DC",
  },
  {
    name: "Flash",
    age: 28,
    city: "Central City",
    realName: "Barry Allen",
    superPower: 90,
    species: "Metahuman",
    company: "DC",
  },
  {
    name: "Aquaman",
    age: 35,
    city: "Atlantis",
    realName: "Arthur Curry",
    superPower: 88,
    species: "Atlantean/Human Hybrid",
    company: "DC",
  },
  {
    name: "Green Lantern",
    age: 32,
    city: "Coast City",
    realName: "Hal Jordan",
    superPower: 87,
    species: "Human (with Power Ring)",
    company: "DC",
  },
  {
    name: "Spider-Man",
    age: 25,
    city: "New York",
    realName: "Peter Parker",
    superPower: 86,
    species: "Human (Mutated)",
    company: "Marvel",
  },
  {
    name: "Iron Man",
    age: 45,
    city: "Malibu",
    realName: "Tony Stark",
    superPower: 82,
    species: "Human",
    company: "Marvel",
  },
  {
    name: "Captain America",
    age: 105,
    city: "Brooklyn",
    realName: "Steve Rogers",
    superPower: 84,
    species: "Human (Super Soldier)",
    company: "Marvel",
  },
  {
    name: "Thor",
    age: 1500,
    city: "Asgard",
    realName: "Thor Odinson",
    superPower: 97,
    species: "Asgardian",
    company: "Marvel",
  },
  {
    name: "Hulk",
    age: 40,
    city: "Dayton",
    realName: "Bruce Banner",
    superPower: 96,
    species: "Human (Gamma Mutated)",
    company: "Marvel",
  },
  {
    name: "Black Widow",
    age: 35,
    city: "Stalingrad",
    realName: "Natasha Romanoff",
    superPower: 78,
    species: "Human",
    company: "Marvel",
  },
  {
    name: "Doctor Strange",
    age: 42,
    city: "New York",
    realName: "Stephen Strange",
    superPower: 92,
    species: "Human (Mystic)",
    company: "Marvel",
  },
  {
    name: "Black Panther",
    age: 35,
    city: "Wakanda",
    realName: "T'Challa",
    superPower: 89,
    species: "Human (Enhanced)",
    company: "Marvel",
  },
  {
    name: "Wolverine",
    age: 137,
    city: "Alberta",
    realName: "Logan",
    superPower: 91,
    species: "Mutant",
    company: "Marvel",
  },
];

// La suma del nivel de poder de todos los humanos menores de 40 años
const total = superheroes
  .map((superhero) => ({
    nombre: superhero.name,
    edad: superhero.age,
    nivel: superhero.superPower,
    especie: superhero.species,
  }))
  .filter(
    (superhero) => superhero.especie.includes("Human") && superhero.edad < 40
  )
  .reduce((acc, superhero) => {
    return acc + superhero.nivel;
  }, 0);
